### ISSUE TITLE
Support for sbd Package

### ISSUE THREAD

**Issue by o** [phax/ph-sbdh#1]
Hello Philip!

We talked about this feature in previous issue. I opened separate issue for that.
[package-package-proxy-ubl21.zip](https://github.com/phax/ph-sbdh/files/112192/package-package-proxy-ubl21.zip)

Thanks!

**Comment by o** [comment]
Oh sorry, looks like you'd done this in ph-ubl https://github.com/phax/ph-ubl/commit/cd85f3003cfd97fdd9ef44331cc0d28485060d91

Closing.

**Comment by phax** [comment]
Okay, you noticed it :) 
I put it in ph-ubl because I thought this is more a UBLTR feature than an SBD feature.
